version: '{branch}-{build}'
image: Visual Studio 2017
configuration: Release
platform: Any CPU
build_script:
- ps: >-
    git config --global core.autocrlf true

    if($env:appveyor_pull_request_number) {
       Update-AppveyorBuild -Version "pr--$env:appveyor_repo_branch-$env:appveyor_build_number-$($env:appveyor_repo_commit.substring(0,7))"
    } else {
       Update-AppveyorBuild -Version "$env:appveyor_repo_branch-$env:appveyor_build_number-$($env:appveyor_repo_commit.substring(0,7))"
    }

    dotnet --version

    dotnet build SRLApiClient/SRLApiClient.csproj -c Release

    dotnet build Tests/Tests.csproj -c Release

test_script:
- ps: >-
    dotnet test Tests/
deploy: off