trigger:
  branches:
    include:
      - azure-pipelines

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.14'
    windows:
      imageName: 'win1803'

pool:
  vmImage: $(imageName)

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.2'
- task: DotNetCoreCLI@2
  displayName: 'Dotnet Version'
  inputs:
    arguments: '--version'
- task: DotNetCoreCLI@2
  displayName: 'Build SRLApiClient'
  inputs:
    command: build
    projects: 'SRLApiClient/SRLApiClient.csproj'
    arguments: '-c Release'
- task: DotNetCoreCLI@2
  displayName: 'Build Tests'
  inputs:
    command: build
    projects: 'Tests/Tests.csproj'
    arguments: '-c Release'
- task: DotNetCoreCLI@2
  displayName: 'Run Tests'
  inputs:
    command: test
    projects: 'Tests/Tests.csproj'
    arguments: '-c Release --no-build'